# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64f1b79eaf0dafcb4e06aa58e42876e6430a93ca361398b8b5b57a1308762e2da0e4687fbd246b0a778c4949ba5dd49843dc8d8250b89d69f03a2ca4dc6b136f

test:
  secret_key_base: 70b764110f5237ae2fe5530dbaf706825b1f2a3f3fe47b5a462f191a2bdd782ebedd11ea0097b4320b61acda25b5444732bd26ab9d394a613b835feb77178f77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
